import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { KB_DIR } from '../kb-lib';
import { GCSIM_DIR, gcsimCommit, gcsimUrl } from './gcsim';
import { RETRIEVED, GAME_VERSION } from './lib';

/**
 * Regenerate kb/mechanics/icd.json from gcsim's generated ICD tables (numbers only).
 *   group id = lowerCamel of the Go constant; gcsim's `Default` group is stored as `standard`.
 *   pattern  = ICDGroupEleApplicationSequence (1 = the hit applies its element; the last value repeats)
 *   resetFrames = ICDGroupResetTimer
 */
const rel = 'pkg/core/attacks/icd_groups.dm.go';
const src = readFileSync(join(GCSIM_DIR, rel), 'utf8');

const constNames = [...src.matchAll(/^\tICDGroup(\w+)(?: ICDGroup = iota)?\s*$/gm)].map((m) => m[1]!);
const block = (name: string) => {
  const m = new RegExp(`var ${name} = [^{]*\\{([\\s\\S]*?)\\n\\}`, 'm').exec(src);
  if (!m) throw new Error(`table ${name} not found`);
  return m[1]!;
};
const lower = (s: string) => s.charAt(0).toLowerCase() + s.slice(1);

const resets = new Map<string, number>();
for (const m of block('ICDGroupResetTimer').matchAll(/ICDGroup(\w+):\s*(\d+)/g)) resets.set(m[1]!, Number(m[2]));
const seqs = new Map<string, number[]>();
for (const m of block('ICDGroupEleApplicationSequence').matchAll(/ICDGroup(\w+):\s*\{([^}]*)\}/g)) {
  seqs.set(m[1]!, m[2]!.split(',').map((s) => Number(s.trim())).filter((n) => !Number.isNaN(n)).map((n) => (n > 0 ? 1 : 0)));
}

const groups: Record<string, { pattern: number[]; resetFrames: number; notes?: string }> = {
  none: { pattern: [1], resetFrames: 0, notes: 'No ICD: every hit applies.' },
};
for (const name of constNames) {
  const seq = seqs.get(name);
  const reset = resets.get(name);
  if (!seq || reset === undefined) continue;
  // trim the repeated tail but keep at least the last value
  let end = seq.length;
  while (end > 1 && seq[end - 1] === seq[end - 2]) end--;
  groups[name === 'Default' ? 'standard' : lower(name)] = { pattern: seq.slice(0, Math.max(end, 1)), resetFrames: reset };
}
groups.standard!.notes = 'gcsim Default group: applies on hits 1, 4, 7... within 2.5 s of the first hit.';
// The default pattern is periodic ([1,0,0] repeating); keep the full generated sequence so clamping matches gcsim.
groups.standard!.pattern = seqs.get('Default')!;

const out = {
  id: 'icd',
  provenance: {
    sources: [{ site: 'gcsim', url: gcsimUrl(rel), retrieved: RETRIEVED, commit: gcsimCommit(), fields: ['ICDGroupEleApplicationSequence', 'ICDGroupResetTimer'] }],
    conflicts: [],
    gameVersion: GAME_VERSION,
  },
  dataConfidence: 'medium',
  assumptions: [
    'Generated by scripts/kb-import/import-icd.ts. The pattern is indexed by the hit count since the sequence started; past the end the last value repeats. Trailing repeats are trimmed except for `standard`.',
    "Tags are free-form per character in the KB; only the group decides the pattern. gcsim also keys the counter by (character, tag, group), which the engine mirrors.",
  ],
  groups,
};
writeFileSync(join(KB_DIR, 'mechanics', 'icd.json'), JSON.stringify(out, null, 2) + '\n');
console.log(`icd.json: ${Object.keys(groups).length} groups`);
